version: '3'
services:
  opendata:
    image: 'diwise/api-opendata:latest'
    build: 
        context: ..
        dockerfile: ./deployments/Dockerfile
    restart: always
    environment: 
      DIWISE_CONTEXT_BROKER_URL: $DIWISE_CONTEXT_BROKER_URL
      WATER_QUALITY_QUERY_PARAMS: $WATER_QUALITY_QUERY_PARAMS
      STRATSYS_COMPANY_CODE: $STRATSYS_COMPANY_CODE
      STRATSYS_CLIENT_ID: $STRATSYS_CLIENT_ID
      STRATSYS_SCOPE: $STRATSYS_SCOPE
      STRATSYS_LOGIN_URL: $STRATSYS_LOGIN_URL
      STRATSYS_DEFAULT_URL: $STRATSYS_DEFAULT_URL
    
    ports:
      - '8088:8080'
