version: '3'
services:
  opendata:
    image: 'diwise/api-opendata:latest'
    build: 
        context: ..
        dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on: 
      - pointofinterest
      - rabbitmq
    links:
      - pointofinterest
      - rabbitmq
    
    ports:
      - '8282'

  pointofinterest:
    image: 'docker.pkg.github.com/diwise/api-pointofinterest/api-pointofinterest:prod-87b47abf442fe17cbbf783b4b6294902fb183666'
    restart: always
    links: 
      - rabbitmq
    environment: 
      SOURCE_DATA_URL: $SOURCE_DATA_URL
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_USER: 'user'
      RABBITMQ_PASS: 'bitnami'
    
    ports:
      - '8585'

  rabbitmq:
    image: 'arm64v8/rabbitmq:3.8' #temporary image to work on Apple M1
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'bitnami'
    ports:
      - '4369'
      - '5672'
      - '25672'
      - '15672'
    volumes:
      - 'rabbitmq_data:/bitnami'

volumes:
  rabbitmq_data:
    driver: local