// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package beaches

import (
	"context"
	"sync"
)

// Ensure, that BeachServiceMock does implement BeachService.
// If this is not the case, regenerate this file with moq.
var _ BeachService = &BeachServiceMock{}

// BeachServiceMock is a mock implementation of BeachService.
//
// 	func TestSomethingThatUsesBeachService(t *testing.T) {
//
// 		// make and configure a mocked BeachService
// 		mockedBeachService := &BeachServiceMock{
// 			BrokerFunc: func() string {
// 				panic("mock out the Broker method")
// 			},
// 			GetAllFunc: func(ctx context.Context) []Beach {
// 				panic("mock out the GetAll method")
// 			},
// 			GetByIDFunc: func(ctx context.Context, id string) (*Beach, error) {
// 				panic("mock out the GetByID method")
// 			},
// 			RefreshFunc: func(contextMoqParam context.Context) (int, error) {
// 				panic("mock out the Refresh method")
// 			},
// 			ShutdownFunc: func(contextMoqParam context.Context)  {
// 				panic("mock out the Shutdown method")
// 			},
// 			StartFunc: func(contextMoqParam context.Context)  {
// 				panic("mock out the Start method")
// 			},
// 			TenantFunc: func() string {
// 				panic("mock out the Tenant method")
// 			},
// 		}
//
// 		// use mockedBeachService in code that requires BeachService
// 		// and then make assertions.
//
// 	}
type BeachServiceMock struct {
	// BrokerFunc mocks the Broker method.
	BrokerFunc func() string

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(ctx context.Context) []Beach

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id string) (*Beach, error)

	// RefreshFunc mocks the Refresh method.
	RefreshFunc func(contextMoqParam context.Context) (int, error)

	// ShutdownFunc mocks the Shutdown method.
	ShutdownFunc func(contextMoqParam context.Context)

	// StartFunc mocks the Start method.
	StartFunc func(contextMoqParam context.Context)

	// TenantFunc mocks the Tenant method.
	TenantFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Broker holds details about calls to the Broker method.
		Broker []struct {
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Refresh holds details about calls to the Refresh method.
		Refresh []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// Shutdown holds details about calls to the Shutdown method.
		Shutdown []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// Tenant holds details about calls to the Tenant method.
		Tenant []struct {
		}
	}
	lockBroker   sync.RWMutex
	lockGetAll   sync.RWMutex
	lockGetByID  sync.RWMutex
	lockRefresh  sync.RWMutex
	lockShutdown sync.RWMutex
	lockStart    sync.RWMutex
	lockTenant   sync.RWMutex
}

// Broker calls BrokerFunc.
func (mock *BeachServiceMock) Broker() string {
	if mock.BrokerFunc == nil {
		panic("BeachServiceMock.BrokerFunc: method is nil but BeachService.Broker was just called")
	}
	callInfo := struct {
	}{}
	mock.lockBroker.Lock()
	mock.calls.Broker = append(mock.calls.Broker, callInfo)
	mock.lockBroker.Unlock()
	return mock.BrokerFunc()
}

// BrokerCalls gets all the calls that were made to Broker.
// Check the length with:
//     len(mockedBeachService.BrokerCalls())
func (mock *BeachServiceMock) BrokerCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockBroker.RLock()
	calls = mock.calls.Broker
	mock.lockBroker.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *BeachServiceMock) GetAll(ctx context.Context) []Beach {
	if mock.GetAllFunc == nil {
		panic("BeachServiceMock.GetAllFunc: method is nil but BeachService.GetAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc(ctx)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//     len(mockedBeachService.GetAllCalls())
func (mock *BeachServiceMock) GetAllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *BeachServiceMock) GetByID(ctx context.Context, id string) (*Beach, error) {
	if mock.GetByIDFunc == nil {
		panic("BeachServiceMock.GetByIDFunc: method is nil but BeachService.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//     len(mockedBeachService.GetByIDCalls())
func (mock *BeachServiceMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// Refresh calls RefreshFunc.
func (mock *BeachServiceMock) Refresh(contextMoqParam context.Context) (int, error) {
	if mock.RefreshFunc == nil {
		panic("BeachServiceMock.RefreshFunc: method is nil but BeachService.Refresh was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockRefresh.Lock()
	mock.calls.Refresh = append(mock.calls.Refresh, callInfo)
	mock.lockRefresh.Unlock()
	return mock.RefreshFunc(contextMoqParam)
}

// RefreshCalls gets all the calls that were made to Refresh.
// Check the length with:
//     len(mockedBeachService.RefreshCalls())
func (mock *BeachServiceMock) RefreshCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockRefresh.RLock()
	calls = mock.calls.Refresh
	mock.lockRefresh.RUnlock()
	return calls
}

// Shutdown calls ShutdownFunc.
func (mock *BeachServiceMock) Shutdown(contextMoqParam context.Context) {
	if mock.ShutdownFunc == nil {
		panic("BeachServiceMock.ShutdownFunc: method is nil but BeachService.Shutdown was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockShutdown.Lock()
	mock.calls.Shutdown = append(mock.calls.Shutdown, callInfo)
	mock.lockShutdown.Unlock()
	mock.ShutdownFunc(contextMoqParam)
}

// ShutdownCalls gets all the calls that were made to Shutdown.
// Check the length with:
//     len(mockedBeachService.ShutdownCalls())
func (mock *BeachServiceMock) ShutdownCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockShutdown.RLock()
	calls = mock.calls.Shutdown
	mock.lockShutdown.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *BeachServiceMock) Start(contextMoqParam context.Context) {
	if mock.StartFunc == nil {
		panic("BeachServiceMock.StartFunc: method is nil but BeachService.Start was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	mock.StartFunc(contextMoqParam)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//     len(mockedBeachService.StartCalls())
func (mock *BeachServiceMock) StartCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// Tenant calls TenantFunc.
func (mock *BeachServiceMock) Tenant() string {
	if mock.TenantFunc == nil {
		panic("BeachServiceMock.TenantFunc: method is nil but BeachService.Tenant was just called")
	}
	callInfo := struct {
	}{}
	mock.lockTenant.Lock()
	mock.calls.Tenant = append(mock.calls.Tenant, callInfo)
	mock.lockTenant.Unlock()
	return mock.TenantFunc()
}

// TenantCalls gets all the calls that were made to Tenant.
// Check the length with:
//     len(mockedBeachService.TenantCalls())
func (mock *BeachServiceMock) TenantCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockTenant.RLock()
	calls = mock.calls.Tenant
	mock.lockTenant.RUnlock()
	return calls
}
